/// Flutter icons AppIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData comment = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_border = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_border = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_border = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_border = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
